// Universities Action Types
export const FETCH_UNIVERSITY_REQUEST = "FETCH_UNIVERSITY_REQUEST";
export const FETCH_UNIVERSITY_SUCCESS = "FETCH_UNIVERSITY_SUCCESS";
export const FETCH_UNIVERSITY_FAIL = "FETCH_UNIVERSITY_FAIL";

// Country Action Types
export const FETCH_COUNTRY_REQUEST = "FETCH_COUNTRY_REQUEST";
export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_FAIL = "FETCH_COUNTRY_FAIL";
