// Universities Action Types
export const FETCH_UNIVERSITY_REQUEST = "FETCH_UNIVERSITY_REQUEST";
export const FETCH_UNIVERSITY_SUCCESS = "FETCH_UNIVERSITY_SUCCESS";
export const FETCH_UNIVERSITY_FAIL = "FETCH_UNIVERSITY_FAIL";

// Country Action Types
export const FETCH_COUNTRY_REQUEST = "FETCH_COUNTRY_REQUEST";
export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_FAIL = "FETCH_COUNTRY_FAIL";

// User Action Types
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

// Errors And Alert
export const GET_ERRORS = "GET_ERRORS";

// Messages
export const GET_MESSAGE = "GET_MESSAGE";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
